name: Deploy EC2 and DynamoDB with Terraform
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.3.0"  # Especifica la versión de Terraform que deseas usar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Debug AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        shell: bash

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform (Crear DynamoDB)
        run: terraform plan -target=aws_dynamodb_table.terraform_state_lock

      - name: Apply Terraform (Crear DynamoDB)
        run: terraform apply -target=aws_dynamodb_table.terraform_state_lock -auto-approve

      - name: Plan Terraform (Crear EC2)
        run: terraform plan -var="instance_name=${{ secrets.INSTANCE_NAME }}"

      - name: Apply Terraform (Crear EC2)
        run: terraform apply -var="instance_name=${{ secrets.INSTANCE_NAME }}" -auto-approve

      - name: Output instance information
        run: terraform output
